# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-05 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20160518_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['teamname']},
        ),
    ]
