# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-05 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_auto_20160606_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='accept',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
