# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-05 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_match_accept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='accept',
            new_name='accept1',
        ),
    ]
