# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-05 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_auto_20160606_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='accept2',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
