# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-06 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_match_accept2'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='reject',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
